services:
  moxie_db:
    restart: always
    container_name: moxie-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  moxie_backend:
    build: .
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    depends_on:
      moxie_db:
        condition: service_healthy
    env_file:
      - ./config/envs/.env.dev
    restart: on-failure