# Generated by Django 4.1 on 2024-09-27 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='medspa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.medspa'),
        ),
    ]
